### ISSUE TITLE
Docker Hub wrong version - 0.4.0

### ISSUE THREAD

**Issue by arthur-leclerc** [jrasell/sherpa#118]
**Describe the bug**

The latest version pushed on Docker Hub does not seem to be the right one.

The interface displays version `0.3.0` instead of `0.4.0` and the digest (`a73972f6f7bd`) is the same on the [Docker Hub](https://hub.docker.com/r/jrasell/sherpa/tags) for both versions.

[Build](https://hub.docker.com/layers/jrasell/sherpa/0.4.0/images/sha256-a73972f6f7bd77f495fc8286fa6913a90053486542f5c2743964319ea400dfee) also show version `0.3.0`.

Seem likes you forgot to bump up version in the [Dockerfile](https://github.com/jrasell/sherpa/blob/master/Dockerfile#L6).

**To reproduce**

```bash
docker run -it --rm -p 8000:8000 jrasell/sherpa:0.4.0 server --bind-addr 0.0.0.0 --ui
```

Hit http://127.0.0.1:8000/ui, version `0.3.0` is displayed.

**Expected behavior**

Sherpa at version `0.4.0`.

**Comment by jrasell** [comment]
@arthur-leclerc thanks and sorry about this! This should now be resolved.
