### ISSUE TITLE
The policy list command while using storage-consul backend fails to list policies

### ISSUE THREAD

**Issue by mylesw42** [jrasell/sherpa#27]
**Describe the bug**
I have a local dev instance of consul and nomad running. Latest 0.0.2+dev build of sherpa. When using the storage-consul backend for policies, the "sherpa policy list" command will fail to list the policies.

**To reproduce**
Start up local consul -dev and nomad -dev instances. Start sherpa locally using the storage-consul-enabled flag.

`$./sherpa policy init http-echo > http-echo.policy`

`$ jq . http-echo.policy`

> {
  "Enabled": true,
  "MaxCount": 16,
  "MinCount": 4,
  "ScaleOutCount": 2,
  "ScaleInCount": 2,
  "ScaleOutCPUPercentageThreshold": 75,
  "ScaleOutMemoryPercentageThreshold": 75,
  "ScaleInCPUPercentageThreshold": 30,
  "ScaleInMemoryPercentageThreshold": 30
}

`$./sherpa policy write --policy-group-name="http-echo" http-echo http-echo.policy`
Successfully wrote job group scaling policy

`$./sherpa policy read http-echo`
Group      Enabled  MinCount  MaxCount  ScaleInCount  ScaleOutCount
http-echo  true     4         16        2             2

`$./sherpa policy list`
Error querying policy list: unexpected response code 500: failed to unmarshal Consul KV value: unexpected end of JSON input

**Expected behavior**
I expect to see the output of all policies defined within the storage-consul backend

**Environment:**
* Sherpa server information (retrieve with `sherpa system info`):
Nomad Address                http://127.0.0.1:4646
Policy Engine                Sherpa API
Policy Storage Backend       Consul
Internal AutoScaling Engine  false
Strict Policy Checking       true

* Sherpa CLI version (retrieve with `sherpa --version`):
sherpa version v0.0.2+dev
	Date:   2019-08-25 18:27:10.534241 +0000 UTC
	Commit: ba37aaa
	Branch: master
	State:  clean

* Server Operating System/Architecture:
MacOS 10.14 / Darwin 

* Sherpa server configuration parameters:
$./sherpa server --storage-consul-enabled --log-enable-dev --log-level=debug

* Nomad client configuration parameters (if any):
$./nomad agent -dev

* Consul client configuration parameters (if any):
$./consul agent -dev -enable-script-checks -node=web -ui

**Additional context**

Sherpa debug log:
```
12:11PM INF pkg/server/server.go:49 > starting HTTP server addr=127.0.0.1:8000
12:11PM INF pkg/server/server.go:65 > Sherpa server configuration server={"autoscaler-enabled":false,"autoscaler-evaluation-interval":60,"bind-addr":"127.0.0.1","bind-port":8000,"policy-engine-api-enabled":true,"policy-engine-nomad-meta-enabled":false,"policy-engine-strict-checking-enabled":true,"storage-consul-enabled":true,"storage-consul-path":"sherpa/policies/"} telemetry={"telemetry-statsd-address":"","telemetry-statsite-address":""} tls={"tls-cert-key-path":"","tls-cert-path":""}
12:11PM DBG pkg/server/server.go:137 > setting up Nomad client
12:11PM DBG pkg/server/server.go:128 > setting up Consul storage backend
12:11PM DBG pkg/server/routes.go:20 > setting up HTTP server routes
12:11PM INF pkg/server/routes.go:90 > starting Sherpa API policy engine
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint GetSystemHealth method=GET path=/v1/system/health
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint GetSystemInfo method=GET path=/v1/system/info
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint GetSystemMetrics method=GET path=/v1/system/metrics
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint ScaleOutJobGroup method=PUT path=/v1/scale/out/{job_id}/{group}
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint ScaleInJobGroup method=PUT path=/v1/scale/in/{job_id}/{group}
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint GetJobScalingPolicies method=GET path=/v1/policies
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint GetJobScalingPolicy method=GET path=/v1/policy/{job_id}
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint GetJobGroupScalingPolicy method=GET path=/v1/policy/{job_id}/{group}
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint PostJobScalingPolicy method=POST path=/v1/policy/{job_id}
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint PostJobGroupScalingPolicy method=POST path=/v1/policy/{job_id}/{group}
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint DeleteJobGroupScalingPolicy method=DELETE path=/v1/policy/{job_id}/{group}
12:11PM INF pkg/server/router/router.go:29 > mounting route endpoint DeleteJobScalingPolicy method=DELETE path=/v1/policy/{job_id}
12:11PM INF pkg/server/server.go:103 > HTTP server successfully listening addr=127.0.0.1:8000
12:11PM INF pkg/server/middleware.go:25 > server responded to request method=POST path=/v1/policy/http-echo/http-echo remote-addr=127.0.0.1:63953 response-code=201
12:11PM ERR pkg/policy/v1/policies.go:28 > failed to call policy backend error="failed to unmarshal Consul KV value: unexpected end of JSON input"
12:11PM INF pkg/server/middleware.go:25 > server responded to request method=GET path=/v1/policies remote-addr=127.0.0.1:63971 response-code=500
12:13PM INF pkg/server/middleware.go:25 > server responded to request method=POST path=/v1/policy/http-echo/http-echo remote-addr=127.0.0.1:64028 response-code=201
12:13PM INF pkg/server/middleware.go:25 > server responded to request method=GET path=/v1/policy/http-echo remote-addr=127.0.0.1:64039 response-code=200
12:13PM ERR pkg/policy/v1/policies.go:28 > failed to call policy backend error="failed to unmarshal Consul KV value: unexpected end of JSON input"
12:13PM INF pkg/server/middleware.go:25 > server responded to request method=GET path=/v1/policies remote-addr=127.0.0.1:64045 response-code=500
```

**Comment by jrasell** [comment]
thanks for the report @mylesw42, i'll look into this as soon as I can

**Comment by mylesw42** [comment]
@jrasell no problem. On further inspection, it appears to also affect the sherpa internal autoscaler capabilities.

12:34PM ERR pkg/autoscale/handler.go:63 > autoscaler unable to get scaling policies error="failed to unmarshal Consul KV value: unexpected end of JSON input"

**Comment by jrasell** [comment]
@mylesw42 yeah, the internal autoscaler relies on reading out the polices in order to understand which jobs to look at on the cluster. I have quickly ran the commands locally as you have described and have not seen the issue. If you can, could you post the consul and nomad version you are also using so I can try and match your env as closely as possible?

**Comment by mylesw42** [comment]
Interesting. Sure thing.

==> Starting Consul agent...
           Version: 'v1.5.3'
           Node ID: '06764586-5110-ec2e-d564-96d2e9e6012b'
         Node name: 'web'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: 8502, DNS: 8600)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false

==> No configuration files loaded
==> Starting Nomad agent...
==> Nomad agent configuration:

       Advertise Addrs: HTTP: 127.0.0.1:4646; RPC: 127.0.0.1:4647; Serf: 127.0.0.1:4648
            Bind Addrs: HTTP: 127.0.0.1:4646; RPC: 127.0.0.1:4647; Serf: 127.0.0.1:4648
                Client: true
             Log Level: DEBUG
                Region: global (DC: dc1)
                Server: true
               Version: 0.9.4

**Comment by mylesw42** [comment]
@jrasell Ohhh, odd. When I started my consul environment I created the "sherpa/policies/" root, and then added the policy with the sherpa command. The policy is added, but the list command fails. 

When I removed the key structure altogether and recreated the policy just using sherpa commands, then the policy list command worked. I'm not sure what to make of that. There were no spelling mistakes.

**Comment by mylesw42** [comment]
Creating "sherpa/policies/" manually, and then populating policies with sherpa commands:

$ consul kv get --recurse sherpa/
sherpa/policies/:
sherpa/policies/http-echo/http-echo:{"Enabled":true,"MinCount":4,"MaxCount":16,"ScaleOutCount":2,"ScaleInCount":2,"ScaleOutCPUPercentageThreshold":75,"ScaleOutMemoryPercentageThreshold":75,"ScaleInCPUPercentageThreshold":30,"ScaleInMemoryPercentageThreshold":30}

Creating from sherpa only:

$ consul kv get --recurse sherpa/
sherpa/policies/http-echo/http-echo:{"Enabled":true,"MinCount":4,"MaxCount":16,"ScaleOutCount":2,"ScaleInCount":2,"ScaleOutCPUPercentageThreshold":75,"ScaleOutMemoryPercentageThreshold":75,"ScaleInCPUPercentageThreshold":30,"ScaleInMemoryPercentageThreshold":30}

I guess we can close this. I went about things a bit out of order I guess :) What do you think?

**Comment by mylesw42** [comment]
I guess it's best to leave the creation of the storage backend structure to the software. Not sure why I thought I need to populate Consul. Sorry for the goose chase!
