### ISSUE TITLE
Incorrect response code and error when API scaling breaks limits

### ISSUE THREAD

**Issue by jrasell** [jrasell/sherpa#59]
**Describe the bug**
When attempting to scale a job by a count which will break the configured policy thresholds, the returned error is empty and the response code is 304. The error should include details of what problem occurred. The response code should be 403, to indicate the request contained valid parameters, but was rejected by the server.

**Comment by pmcatominey** [comment]
My suggestion for this would be to use 409 or 412 to avoid any confusion with auth with is where 403 is most commonly used.

**Comment by jrasell** [comment]
good shout @pmcatominey
